package com.cinebook.movieservice.service;

import com.cinebook.movieservice.entity.User;
import com.cinebook.movieservice.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.Optional;

@Service
public class AuthService {

    @Autowired
    private UserRepository userRepo;

    // Use a Bean for PasswordEncoder if defined in your SecurityConfig, 
    // otherwise this local instance works for basic setup.
    private final PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

    /**
     * Registers a new user into MongoDB Atlas.
     * The ID will be auto-generated by MongoDB as a String (ObjectId).
     */
    public User register(String name, String email, String password) {
        // existsByEmail works automatically with Spring Data MongoDB
        if (userRepo.existsByEmail(email)) {
            throw new RuntimeException("Email already exists in our records.");
        }

        String encodedPassword = passwordEncoder.encode(password);
        
        // Creating the User document object
        User newUser = new User(name, email, encodedPassword);
        
        // save() returns the User with its new MongoDB String ID populated
        return userRepo.save(newUser);
    }

    /**
     * Authenticates a user against MongoDB records.
     */
    public User login(String email, String password) {
        // findByEmail is a derived query generated for MongoDB
        Optional<User> userOpt = userRepo.findByEmail(email);
        
        if (userOpt.isPresent()) {
            User user = userOpt.get();
            
            // matches() compares the raw password with the BCrypt hash from Atlas
            if (passwordEncoder.matches(password, user.getPasswordHash())) {
                return user;
            }
        }
        
        // Generic error for security best practices
        throw new RuntimeException("Invalid email or password");
    }
}